import { Application } from "../types";

export const mockApplications: Application[] = [
  {
    id: "1",
    name: "Music Finder Bot",
    category: "Музыка",
    shortDescription: "Находит любую музыку по названию или тексту песни",
    fullDescription: "Music Finder Bot - это мощный инструмент для поиска музыки в Telegram. Просто отправьте название песни или часть текста, и бот найдет нужный трек. Поддерживает поиск по исполнителю, альбому и жанру. Высокое качество аудио до 320 kbps.",
    link: "https://t.me/musicfinderbot",
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=300&fit=crop",
    tags: ["музыка", "поиск", "аудио"],
    date: "2025-10-22",
    status: "approved",
    type: "bot",
    createdAt: "2025-10-22T10:00:00Z",
    updatedAt: "2025-10-22T10:00:00Z"
  },
  {
    id: "2",
    name: "Tech News Channel",
    category: "Новости",
    shortDescription: "Актуальные новости из мира технологий",
    fullDescription: "Канал о последних технологических новостях, обзорах гаджетов и IT-трендах. Публикуем материалы несколько раз в день. Только проверенная информация из надежных источников. Подписывайтесь, чтобы быть в курсе всех событий tech-индустрии.",
    link: "https://t.me/technewschannel",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400&h=300&fit=crop",
    tags: ["новости", "технологии", "гаджеты"],
    date: "2025-10-21",
    status: "approved",
    type: "channel",
    createdAt: "2025-10-21T10:00:00Z",
    updatedAt: "2025-10-21T10:00:00Z"
  },
  {
    id: "3",
    name: "Developers Chat",
    category: "Технологии",
    shortDescription: "Сообщество разработчиков для обмена опытом",
    fullDescription: "Активное сообщество программистов, где можно задать вопросы, поделиться опытом и найти решение технических проблем. Обсуждаем JavaScript, Python, Go, React и многое другое. Дружелюбная атмосфера и взаимопомощь.",
    link: "https://t.me/developerschat",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400&h=300&fit=crop",
    tags: ["программирование", "разработка", "сообщество"],
    date: "2025-10-20",
    status: "approved",
    type: "group",
    createdAt: "2025-10-20T10:00:00Z",
    updatedAt: "2025-10-20T10:00:00Z"
  },
  {
    id: "4",
    name: "English Learning Bot",
    category: "Образование",
    shortDescription: "Изучайте английский язык с интерактивным ботом",
    fullDescription: "Бот для изучения английского языка с ежедневными уроками, тестами и практикой. Включает словарь, грамматические упражнения и разговорную практику. Адаптивная система обучения подстраивается под ваш уровень знаний.",
    link: "https://t.me/englishlearningbot",
    image: "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=400&h=300&fit=crop",
    tags: ["образование", "английский", "обучение"],
    date: "2025-10-19",
    status: "approved",
    type: "bot",
    createdAt: "2025-10-19T10:00:00Z",
    updatedAt: "2025-10-19T10:00:00Z"
  },
  {
    id: "5",
    name: "Funny Memes",
    category: "Развлечения",
    shortDescription: "Лучшие мемы каждый день",
    fullDescription: "Канал с самыми смешными и актуальными мемами. Публикуем контент несколько раз в день. Только качественный юмор без политики. Поднимем настроение в любой ситуации! Присоединяйтесь к нашему веселому сообществу.",
    link: "https://t.me/funnymemes",
    image: "https://images.unsplash.com/photo-1533158326339-7f3cf2404354?w=400&h=300&fit=crop",
    tags: ["мемы", "юмор", "развлечения"],
    date: "2025-10-18",
    status: "approved",
    type: "channel",
    createdAt: "2025-10-18T10:00:00Z",
    updatedAt: "2025-10-18T10:00:00Z"
  },
  {
    id: "6",
    name: "Weather Bot",
    category: "Инструменты",
    shortDescription: "Прогноз погоды для любого города",
    fullDescription: "Получайте точный прогноз погоды на неделю для любого города мира. Бот показывает температуру, осадки, скорость ветра и влажность. Возможность настроить уведомления о резких изменениях погоды. Данные обновляются каждый час.",
    link: "https://t.me/weatherbot",
    image: "https://images.unsplash.com/photo-1592210454359-9043f067919b?w=400&h=300&fit=crop",
    tags: ["погода", "прогноз", "инструменты"],
    date: "2025-10-17",
    status: "approved",
    type: "bot",
    createdAt: "2025-10-17T10:00:00Z",
    updatedAt: "2025-10-17T10:00:00Z"
  },
  {
    id: "7",
    name: "Crypto Trading Signals",
    category: "Бизнес",
    shortDescription: "Торговые сигналы по криптовалютам",
    fullDescription: "Профессиональные торговые сигналы для криптовалютного рынка. Анализ Bitcoin, Ethereum и альткоинов. Технический и фундаментальный анализ от опытных трейдеров. Средняя точность сигналов 75%. Только для информационных целей.",
    link: "https://t.me/cryptosignals",
    image: "https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=400&h=300&fit=crop",
    tags: ["криптовалюта", "трейдинг", "финансы"],
    date: "2025-10-16",
    status: "approved",
    type: "channel",
    createdAt: "2025-10-16T10:00:00Z",
    updatedAt: "2025-10-16T10:00:00Z"
  },
  {
    id: "8",
    name: "Gaming Community",
    category: "Игры",
    shortDescription: "Сообщество геймеров для совместных игр",
    fullDescription: "Большое сообщество геймеров для поиска тимейтов, обсуждения игр и киберспорта. Регулярные турниры и розыгрыши призов. Поддерживаем CS2, Dota 2, Valorant, Apex Legends и другие популярные игры. Присоединяйтесь!",
    link: "https://t.me/gamingcommunity",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
    tags: ["игры", "геймеры", "киберспорт"],
    date: "2025-10-15",
    status: "approved",
    type: "group",
    createdAt: "2025-10-15T10:00:00Z",
    updatedAt: "2025-10-15T10:00:00Z"
  },
  {
    id: "9",
    name: "Task Manager Bot",
    category: "Инструменты",
    shortDescription: "Управление задачами и напоминания",
    fullDescription: "Простой и удобный бот для управления задачами прямо в Telegram. Создавайте списки дел, устанавливайте напоминания, отслеживайте прогресс. Синхронизация между устройствами, категории задач, повторяющиеся события. Ваш персональный помощник 24/7.",
    link: "https://t.me/taskmanagerbot",
    image: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=400&h=300&fit=crop",
    tags: ["продуктивность", "задачи", "планирование"],
    date: "2025-10-14",
    status: "pending",
    type: "bot",
    createdAt: "2025-10-14T10:00:00Z",
    updatedAt: "2025-10-14T10:00:00Z"
  },
  {
    id: "10",
    name: "Football Fans",
    category: "Спорт",
    shortDescription: "Обсуждение футбола и трансляции матчей",
    fullDescription: "Сообщество футбольных фанатов. Обсуждаем матчи, трансферы, тактику и новости футбола. Ссылки на трансляции важных матчей. Дружелюбная атмосфера без токсичности. Приветствуются болельщики всех клубов!",
    link: "https://t.me/footballfans",
    image: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=400&h=300&fit=crop",
    tags: ["футбол", "спорт", "фанаты"],
    date: "2025-10-13",
    status: "pending",
    type: "group",
    createdAt: "2025-10-13T10:00:00Z",
    updatedAt: "2025-10-13T10:00:00Z"
  }
];
